import pathlib
CONFIG_ROOT = pathlib.Path(__file__).parent.resolve()

ENCODER_ARCHS = ['resnet50', 'vit-base-patch16-224', 'vit-large-patch16-224']

USE_EVAL_DATASET=True
EVAL_DATASET_INFO_PATH= 'imageinwords/datasets'
EVAL_DATASET_SPLIT='IIW-400'

IMG_HEIGHT = 224
IMG_WIDTH = 224
PATCH_SIZE = 16 #112 #16
# NUM_PATCHES = (IMG_HEIGHT // PATCH_SIZE) * (IMG_WIDTH // PATCH_SIZE)

TEXT_VOCAB_SIZE = 1000
TEXT_EMBEDDING_DIM = 300
IMG_EMBEDDING_DIM = 300